server:
  port: ${SERVER_PORT:8765}

spring:
  application:
    name: api-gateway-service

  config:
    import: 'kubernetes:'

  cloud:
    kubernetes:
      discovery:
        enabled: true
        namespaces: default
      config:
        enabled: true
        name: ${spring.application.name}
        namespace: default
        fail-fast: true
        include-profile-specific-sources: false
