apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: {{ .Values.logstash.replicas }}
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: {{ .Values.logstash.image }}
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  type: ClusterIP
  ports:
    - port: 5044
      targetPort: 5044
  selector:
    app: logstash